package unimod;

import com.evelopers.unimod.runtime.ControlledObject;
import com.evelopers.unimod.runtime.context.StateMachineContext;

public class C3 implements ControlledObject {

	/**
	 * @unimod.action.descr train has reached destination
	 */
	public boolean c_reached_dest(StateMachineContext context) {
		/*TODO: automatically generated by UniMod method*/
		return false;
	}

	/**
	 * @unimod.action.descr start inglenook
	 */
	public boolean c_start(StateMachineContext context) {
		/*TODO: automatically generated by UniMod method*/
		return false;
	}

	/**
	 * @unimod.action.descr read from list and start train
	 */
	public boolean c_readlist(StateMachineContext context) {
		
		
		/* read the appropriate parameter*/
		 
		String moveitems[]  = P1.getRouteParameter(context);
		
		String from_branch = moveitems[1]; 	//st1,st2,st3 or sth
		String to_branch = moveitems[2];
		
		/*set the desired route */
		String from = null; 
		switch(from_branch){
		case "st1":
			from = "3_To_Rev";
			break;
		case "st2":
			from = "5_To_Rev";
			break;
		case "st3":
			from = "6_To_Rev";
			break;
		case "sth":
			from = "1_To_For";
			break;
		}
		
		String to = null; 
		switch(to_branch){
		case "st1":
			to = "3_To_For";
			break;
		case "st2":
			to = "5_To_For";
			break;
		case "st3":
			to = "6_To_For";
			break;
		case "sth":
			to = "1_To_Rev";
			break;
		}
		String route;
		if((from != null) && (to != null)){
			route = from + "," + to;
			 /*change the route of the engine 
			 * routes are of the form 1_To_Rev*/ 
			
						
			
		}
		
		/* move the engine */

		
		
		
		return false;
	}
}
