package unimod;

import com.evelopers.unimod.runtime.ControlledObject;
import com.evelopers.unimod.runtime.context.StateMachineContext;

public class C4 implements ControlledObject {

	/**
	 * @unimod.action.descr train has reached destination
	 */
	public boolean reached_dest(StateMachineContext context) {
		/*TODO: automatically generated by UniMod method*/
		return false;
	}

	/**
	 * @unimod.action.descr start inglenook
	 */
	public boolean start(StateMachineContext context) {
		/*TODO: automatically generated by UniMod method*/
		return false;
	}

	/**
	 * @unimod.action.descr finished inglenook
	 */
	public boolean end(StateMachineContext context) {
		/*TODO: automatically generated by UniMod method*/
		return false;
	}

}
